@url_dev=http://localhost:3055/v1/api
@x_api_key=1234567890

### sign up
POST {{url_dev}}/shop/signup
Content-Type: application/json
x-api-key: {{x_api_key}}
{
    "name": "Shop TIPS",
    "email": "shoptipjs@gmail.com",
    "password": "abc123"
}

### login
# @name login
POST {{url_dev}}/shop/login
Content-Type: application/json
x-api-key: {{x_api_key}}

{
    "email": "shoptipjs@gmail.com",
    "password": "ab123"
}

### Common variables for authenticated requests
@accessToken = {{login.response.body.metadata.tokens.accessToken}}
@refreshToken = {{login.response.body.metadata.tokens.refreshToken}}
@clientId = {{login.response.body.metadata.shop._id}}

### logout
POST {{url_dev}}/shop/logout
Content-Type: application/json
x-api-key: {{x_api_key}}
x-client-id: {{clientId}}
authorization: {{accessToken}}

### refresh token
POST {{url_dev}}/shop/refresh-token
Content-Type: application/json
x-api-key: {{x_api_key}}
x-client-id: {{clientId}}
authorization: {{accessToken}}
x-refresh-token: {{refreshToken}}