@accessToken = {{login.response.body.metadata.tokens.accessToken}}
@refreshToken = {{login.response.body.metadata.tokens.refreshToken}}
@clientId = {{login.response.body.metadata.shop._id}}
@product = {{getPublishedProducts.response.body.metadata[0]}}

### 1. login
# @name login
POST {{url_dev}}/shop/login
Content-Type: application/json
x-api-key: {{x_api_key}}

{
    "email": "shoptipjs@gmail.com",
    "password": "abc123"
}

### 2. get published products
# @name getPublishedProducts
GET {{url_dev}}/product/published/all?limit=10&offset=0
Content-Type: application/json
x-api-key: {{x_api_key}}
x-client-id: {{clientId}}
authorization: {{accessToken}}

### 3. checkout review
POST {{url_dev}}/checkout
Content-Type: application/json
x-api-key: {{x_api_key}}

{
    "userId": 1001,
    "cartId": "69f5119a121d3271ece24d26",
     "shop_orderIds": [
        {
            "shopId": "{{getPublishedProducts.response.body.metadata[0].product_shop._id}}",
            "shop_discounts":["SUMMER201"],
            "item_products": [
                {
                    "productId": "{{getPublishedProducts.response.body.metadata[0]._id}}",
                    "shopId": "{{getPublishedProducts.response.body.metadata[0].product_shop._id}}",
                    "quantity": "{{getPublishedProducts.response.body.metadata[0].product_quantity}}",
                    "price": "{{getPublishedProducts.response.body.metadata[0].product_price}}"
                }
            ]
        }
    ]
}