@accessToken = {{login.response.body.metadata.tokens.accessToken}}
@refreshToken = {{login.response.body.metadata.tokens.refreshToken}}
@clientId = {{login.response.body.metadata.shop._id}}
@draftProductId = {{getDraftProducts.response.body.metadata[0]._id}}
@publishedProductId = {{getPublishedProducts.response.body.metadata[0]._id}}

### 1. login
# @name login
POST {{url_dev}}/shop/login
Content-Type: application/json
x-api-key: {{x_api_key}}

{
    "email": "shoptipjs@gmail.com",
    "password": "abc123"
}

### 2. create a product
POST {{url_dev}}/product
Content-Type: application/json
x-api-key: {{x_api_key}}
x-client-id: {{clientId}}
authorization: {{accessToken}}

{
    "product_name" : "Laptop 2",
    "product_description" : "High-performance laptop",
    "product_price" : 1500,
    "product_type" : "Electronics",
    "product_thumb" : "product_thumb",
    "product_quantity" : 5,
    "product_attributes" : {
        "manufacturer": "HP",
        "model": "XPS 15",
        "color": "Silver"
    }
}


### 3. get draft products
# @name getDraftProducts
GET {{url_dev}}/product/drafts/all?limit=10&offset=0
Content-Type: application/json
x-api-key: {{x_api_key}}
x-client-id: {{clientId}}
authorization: {{accessToken}}

### 4. get published products
# @name getPublishedProducts
GET {{url_dev}}/product/published/all?limit=10&offset=0
Content-Type: application/json
x-api-key: {{x_api_key}}
x-client-id: {{clientId}}
authorization: {{accessToken}}


### 5. set publish product
POST {{url_dev}}/product/publish/{{draftProductId}}
Content-Type: application/json
x-api-key: {{x_api_key}}
x-client-id: {{clientId}}
authorization: {{accessToken}}

### 6. set unpublish product
POST {{url_dev}}/product/unpublish/{{publishedProductId}}
Content-Type: application/json
x-api-key: {{x_api_key}}
x-client-id: {{clientId}}
authorization: {{accessToken}}

### 7. search products by user
GET {{url_dev}}/product/search/keySearch?keySearch=high
x-api-key: {{x_api_key}}
x-client-id: {{clientId}}

### 8. get all products
GET {{url_dev}}/product
x-api-key: {{x_api_key}}
x-client-id: {{clientId}}

### 9. get a product
GET {{url_dev}}/product/69f33c5ff07aeb97d599861e
x-api-key: {{x_api_key}}
x-client-id: {{clientId}}

### 10. update a product
PATCH {{url_dev}}/product/69f33c5ff07aeb97d599861e
Content-Type: application/json
x-api-key: {{x_api_key}}
x-client-id: {{clientId}}
authorization: {{accessToken}}

{
   "product_name": "New Jeans 2",
   "product_type": "Clothing",
    "product_attributes": {
      "color": "Levi ssssss"
    }
}