@url_dev=http://localhost:3055/v1/api
@x_api_key=1234567890

### login
# @name login
POST {{url_dev}}/shop/login
Content-Type: application/json
x-api-key: {{x_api_key}}

{
    "email": "shoptipjs@gmail.com",
    "password": "abc123"
}

### set environment variables
@accessToken = {{login.response.body.metadata.tokens.accessToken}}
@refreshToken = {{login.response.body.metadata.tokens.refreshToken}}
@clientId = {{login.response.body.metadata.shop._id}}

### create product
POST {{url_dev}}/product
Content-Type: application/json
x-api-key: {{x_api_key}}
x-client-id: {{clientId}}
authorization: {{accessToken}}

{
    "product_name" : "New Jeans",
    "product_description" : "High-quality denim jeans",
    "product_price" : 50,
    "product_type" : "Clothing",
    "product_thumb" : "product_thumb",
    "product_quantity" : 5,
    "product_attributes" : {
        "brand": "Levi s",
        "size": "L",
        "material": "Denim"
    }
}


### get draft products
# @name getDrafts
GET {{url_dev}}/product/drafts/all?limit=10&offset=0
Content-Type: application/json
x-api-key: {{x_api_key}}
x-client-id: {{clientId}}
authorization: {{accessToken}}

### get published products
# @name getPublishedProducts
GET {{url_dev}}/product/published/all?limit=10&offset=0
Content-Type: application/json
x-api-key: {{x_api_key}}
x-client-id: {{clientId}}
authorization: {{accessToken}}

### set product vars
@draftProductId = {{getDrafts.response.body.metadata[0]._id}}
@publishedProductId = {{getPublishedProducts.response.body.metadata[0]._id}}

### set publish product
POST {{url_dev}}/product/publish/{{draftProductId}}
Content-Type: application/json
x-api-key: {{x_api_key}}
x-client-id: {{clientId}}
authorization: {{accessToken}}

### set unpublish product
POST {{url_dev}}/product/unpublish/{{publishedProductId}}
Content-Type: application/json
x-api-key: {{x_api_key}}
x-client-id: {{clientId}}
authorization: {{accessToken}}

### search product by user
GET {{url_dev}}/product/search/keySearch?keySearch=high
x-api-key: {{x_api_key}}
x-client-id: {{clientId}}